import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Save, Video, Heart, Clock, Music } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const PlaylistDisplay = ({ playlist, onSave, user, onLoginRequired }) => {
  const [savedSongs, setSavedSongs] = useState(new Set());
  const [showSaveSuccess, setShowSaveSuccess] = useState(false);
  const navigate = useNavigate();

  if (!playlist) return null;

  const handleVideoPlay = (song) => {
    navigate(`/video/${encodeURIComponent(song.title + ' ' + song.artist)}`);
  };

  const handleSavePlaylist = () => {
    if (!user) {
      onLoginRequired();
      return;
    }
    onSave(playlist);
    setShowSaveSuccess(true);
    setTimeout(() => setShowSaveSuccess(false), 3000);
  };

  const toggleSaveSong = (songId) => {
    const newSavedSongs = new Set(savedSongs);
    if (newSavedSongs.has(songId)) {
      newSavedSongs.delete(songId);
    } else {
      newSavedSongs.add(songId);
    }
    setSavedSongs(newSavedSongs);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-4xl mx-auto mt-8 p-6 bg-gray-900 rounded-2xl border border-gray-700"
    >
      {/* Success Message */}
      <AnimatePresence>
        {showSaveSuccess && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="mb-4 p-3 bg-green-900/50 border border-green-500/50 rounded-lg text-green-300 text-sm flex items-center space-x-2"
          >
            <Music className="w-4 h-4" />
            <span>Playlist saved to your library!</span>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="flex items-start justify-between mb-6">
        <div className="flex-1">
          <h2 className="text-3xl font-bold text-white mb-2">
            {playlist.title}
          </h2>
          <p className="text-gray-300 text-lg mb-3">{playlist.description}</p>
          <div className="flex items-center space-x-4 text-sm text-gray-400">
            <span className="flex items-center space-x-1">
              <Clock className="w-4 h-4" />
              <span>{playlist.songs?.length || 0} songs</span>
            </span>
            <span>•</span>
            <span>Generated by MoodTunes AI</span>
          </div>
        </div>
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={handleSavePlaylist}
          className="px-6 py-3 bg-green-500 hover:bg-green-400 text-black font-semibold rounded-full transition-all duration-300 flex items-center space-x-2"
        >
          <Save className="w-4 h-4" />
          <span>Save to Library</span>
        </motion.button>
      </div>

      <div className="space-y-2">
        <AnimatePresence>
          {playlist.songs?.map((song, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, x: -50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
              className="group p-4 bg-gray-800/50 hover:bg-gray-700/50 rounded-xl transition-all duration-300 border border-transparent hover:border-gray-600"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-4 flex-1">
                  <div className="w-12 h-12 bg-gradient-to-br from-green-400 to-green-600 rounded-lg flex items-center justify-center text-black font-bold text-lg">
                    {index + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="text-white font-semibold text-lg truncate group-hover:text-green-400 transition-colors">
                      {song.title}
                    </h3>
                    <p className="text-gray-400 text-sm truncate">{song.artist}</p>
                    {song.description && (
                      <p className="text-gray-500 text-xs mt-1 italic truncate">{song.description}</p>
                    )}
                  </div>
                </div>
                
                {/* Action buttons (only Save + Video now) */}
                <div className="flex items-center space-x-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  {/* Save Song */}
                  <motion.button
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    onClick={() => toggleSaveSong(index)}
                    className={`p-2 rounded-full transition-all duration-300 ${
                      savedSongs.has(index) 
                        ? 'bg-green-500 text-black' 
                        : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                    }`}
                  >
                    <Heart className={`w-4 h-4 ${savedSongs.has(index) ? 'fill-current' : ''}`} />
                  </motion.button>
                  
                  {/* Play Video */}
                  <motion.button
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    onClick={() => handleVideoPlay(song)}
                    className="p-2 bg-red-600 hover:bg-red-500 rounded-full text-white transition-all duration-300"
                  >
                    <Video className="w-4 h-4" />
                  </motion.button>
                </div>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
    </motion.div>
  );
};

export default PlaylistDisplay;
